version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
